### ISSUE TITLE
Context menu Play function crash

### ISSUE THREAD

**Issue by dancer69** [elgatito/context.elementum#26]
I haven't use context menu the last months. I tried today and I get error when use play function. 
` ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnboundLocalError'>
                                            Error Contents: local variable 'url' referenced before assignment
                                            Traceback (most recent call last):
                                              File "/home/user/.kodi/addons/context.elementum/context_play.py", line 8, in <module>
                                                doPlay()
                                              File "/home/user/.kodi/addons/context.elementum/plugin.py", line 137, in doPlay
                                                log.info("Starting Elementum with: %s" % url)
                                            UnboundLocalError: local variable 'url' referenced before assignment
                                            -->End of Python script error report<--
2021-07-29 16:05:58.809 T:139716088092224   DEBUG: onExecutionDone(31, /home/user/.kodi/addons/context.elementum/context_play.py)`

**Comment by antonsoroko** [comment]
@dancer69 
please try to replace your local `/home/user/.kodi/addons/context.elementum/plugin.py`
with
https://raw.githubusercontent.com/antonsoroko/context.elementum/hotfix-doPlay/plugin.py

if issue disappear - then fix will be merged.

**Comment by dancer69** [comment]
Thanks for the quick fix.
Yes. With this plugin.py version works!

**Comment by elgatito** [comment]
@dancer69 Should be available with v0.0.10
