### ISSUE TITLE
"Elementum Скачать" курсор баг.

### ISSUE THREAD

**Issue by pavelmxx** [elgatito/context.elementum#7]
При использовании пункта контектного меню "Elementum Скачать", строчка для поиска по трекерам передается не из тогого фильма, по которому вызвал контекстное меню, а из фильма, на котором стоит курсор в текущий момент. Баг актуален при использовании мышки. Если после левого клика по " Elementum Скачать " быстро перевести курсор на другой фильм, то другой фильм и будет искать. На медленных устройствах, при использовании мышки, пользоваться контектным меню весьма затруднительно. Надо приноровиться не шевелить мышь после левого клика.

**Comment by elgatito** [comment]
Коди не передаёт информацию по чём нажали. Дополенние берёт информацию от Коди не напрямую. Обновляется эта информация только когда нажмёшь. Со стороны дополнения я не вижу никаких вариантов.
