### ISSUE TITLE
Not working on Kodi 19

### ISSUE THREAD

**Issue by AlvaroB1982** [elgatito/context.elementum#8]
Hello, thanks for your work, is amazing.
On Kodi 19 when I try to install the helper it give me an error about xbmc.pyton dependence,
Can you fix it? Thanks

**Comment by elgatito** [comment]
@AlvaroB1982 Log file, showing installation, is required.

**Comment by AlvaroB1982** [comment]
Thanks for quick answer,
Here is the log:

https://u.pcloud.link/publink/show?code=XZgH3mXZz683OJhwaY5RotvPOlKX34IE1Vey

Good work

**Comment by AlvaroB1982** [comment]
Maybe this helps:
https://forum.kodi.tv/showthread.php?tid=352247

**Comment by elgatito** [comment]
@AlvaroB1982 Try to install v0.0.4.

**Comment by AlvaroB1982** [comment]
Hello,
Thanks for this quick fix,
No it install ok, and I can see the options on context menu.
But i receive an error when I do 'elementum play'.

https://u.pcloud.link/publink/show?code=XZdnpbXZpSLy90em4bmT4aKmvvPzMkM2xGoX

Thanks again
